config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  get "students/hello", to: "students#hello"
  get "students/about", to: "students#about"
  get "students/status", to: "students#status"
  get "students/greet", to: "students#greet"
  get "students/morning", to:"students#morning"
  post "/students/create", to: "students#create"
  get "/students", to: "students#index"

  # post "/libraries/create", to: "library#create"

  get "/students/sagar", to: "students#sagar"
  post "/students/sagar", to: "students#sagar"

resources :students
resources :libraries
resources :tasks

resources :vehicals
# resources :Students

end

app/models/task.rb
    class Task < ApplicationRecord
        validates :title, presence: true
    end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

def index
    @tasks = Task.all
end

def show
    @task = Task.find(params[:id])
end

def new
    @task = Task.new
end

def create
    @task =Task.new(task_params)
    if @task.save
        redirect_to tasks_path notice:"task created successfully"
    else
        render :new
    end
end

def edit
    @task = Task.find(params[:id])
end

def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
        redirect_to tasks_path, notice: "task updated succesfully"
    else
        render :edit
    end
end

def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: "Task delected sucessfully"
end


private

def task_params
    params.require(:task).permit(:title, :description , :completed)
end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<h1> Edit Tasks</h1>

<%= form_with model:@task do |f| %>
    <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>

    <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
    </div>

    <div>
    <%= f.submit "update task" %>
    </div>
    <% end %>
    

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<%= link_to 'New Task', new_task_path %>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task_path(task) %> |
      <%= button_to "Delete", task_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } %>  
      <%= link_to "Edit", edit_task_path(task),
          meathod: :get %>

    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1> New Tasks </h1>

<%= form_with model: @task do |f| %>
    <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>

    <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
    </div>

    <div>
    <%= f.submit "Create Task" %>
    </div>
<% end %>


<% if @task.errors.any? %>
    <ul>
    <% @task.errors.full_messages.each do |mes| %>
        <li> <%= mes%> </li>
        <% end %>
        </ul>
    <% end %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %> </h1>
<p> <%= @task.description %> </p>

<%= link_to "Back to tasks", tasks_path %>